name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update Versions
      env:
        VERSION_PREFIX: 0.1
        VERSION_SUFFIX: ${{github.run_number}}
      run: |
        VERSION=$VERSION_PREFIX.$VERSION_SUFFIX
        sed -i.bak "s:<Version>1.0.0</Version>:<Version>$VERSION</Version>:g" FbxSharp/FbxSharp.csproj
        sed -i.bak "s:<version>1.0.0</version>:<version>$VERSION</version>:g" FbxSharp.nuspec
        sed -i.bak "s:version=\"1.0.0\":version=\"$VERSION\":g" FbxSharp.nuspec
        sed -i.bak "s:<version>1.0.0</version>:<version>$VERSION</version>:g" FbxSharp.Native.nuspec
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.401
    - name: Restore workloads
      run: dotnet workload restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build native
      run: make native
    - name: Test native
      run: make test
    - name: Build managed
      run: make managed
    - name: Build nugets
      run: make nuget
    - name: Store nugets
      uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: "*.nupkg"
